version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  app:
    build: ./app
    container_name: go-cache-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["go", "run", "main.go"]
    volumes:
      - ./app:/app
    working_dir: /app

volumes:
  redis-data:
